# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Override hypridle with custom config (NVIDIA sleep/wake fix)
exec-once = bash -c "pkill hypridle; hypridle -c ~/.config/hypr/custom/hypridle.conf"

