# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = us
    kb_variant = intl
    # kb_options = grp:alt_space_toggle
    # kb_rules =
    
    # ... other settings
}
